//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHeaven.Reader.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookHeaven.Reader.Resources.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string APPS {
            get {
                return ResourceManager.GetString("APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Profile.
        /// </summary>
        public static string BACKUP_PROFILE {
            get {
                return ResourceManager.GetString("BACKUP_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string BOOKS {
            get {
                return ResourceManager.GetString("BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books matching the current filter.
        /// </summary>
        public static string BOOKS_NO_FILTER_MATCH {
            get {
                return ResourceManager.GetString("BOOKS_NO_FILTER_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Author.
        /// </summary>
        public static string BY_AUTHOR {
            get {
                return ResourceManager.GetString("BY_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string BY_MISSING {
            get {
                return ResourceManager.GetString("BY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the URL and try again.
        /// </summary>
        public static string CHECK_THE_URL {
            get {
                return ResourceManager.GetString("CHECK_THE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established.
        /// </summary>
        public static string CONNECTION_ESTABLISHED {
            get {
                return ResourceManager.GetString("CONNECTION_ESTABLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server.
        /// </summary>
        public static string CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DEFAULT {
            get {
                return ResourceManager.GetString("DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download books.
        /// </summary>
        public static string DOWNLOAD_BOOKS {
            get {
                return ResourceManager.GetString("DOWNLOAD_BOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book has been downloaded.
        /// </summary>
        public static string DOWNLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("DOWNLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string DOWNLOADING {
            get {
                return ResourceManager.GetString("DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string END_DATE {
            get {
                return ResourceManager.GetString("END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your server&apos;s URL.
        /// </summary>
        public static string ENTER_SERVER_URL {
            get {
                return ResourceManager.GetString("ENTER_SERVER_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string FINISHED {
            get {
                return ResourceManager.GetString("FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FONT {
            get {
                return ResourceManager.GetString("FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FONT_SIZE {
            get {
                return ResourceManager.GetString("FONT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Margin.
        /// </summary>
        public static string HORIZONTAL_MARGIN {
            get {
                return ResourceManager.GetString("HORIZONTAL_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only HTTPS protocol is supported.
        /// </summary>
        public static string HTTPS_ONLY {
            get {
                return ResourceManager.GetString("HTTPS_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS is recommended although not enforced.
        /// </summary>
        public static string HTTPS_RECOMMENDED {
            get {
                return ResourceManager.GetString("HTTPS_RECOMMENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some assets from the server (mostly book covers) might not load if using plain HTTP.
        /// </summary>
        public static string HTTPS_RECOMMENDED_INFO {
            get {
                return ResourceManager.GetString("HTTPS_RECOMMENDED_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string IN_PROGRESS {
            get {
                return ResourceManager.GetString("IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string INDEX {
            get {
                return ResourceManager.GetString("INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string INITIALIZING {
            get {
                return ResourceManager.GetString("INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LANG_EN {
            get {
                return ResourceManager.GetString("LANG_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string LANG_ES {
            get {
                return ResourceManager.GetString("LANG_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last read.
        /// </summary>
        public static string LAST_READ {
            get {
                return ResourceManager.GetString("LAST_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter spacing.
        /// </summary>
        public static string LETTER_SPACING {
            get {
                return ResourceManager.GetString("LETTER_SPACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Height.
        /// </summary>
        public static string LINE_HEIGHT {
            get {
                return ResourceManager.GetString("LINE_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your book....
        /// </summary>
        public static string LOADING_BOOK {
            get {
                return ResourceManager.GetString("LOADING_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string LOCAL {
            get {
                return ResourceManager.GetString("LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual connection.
        /// </summary>
        public static string MANUAL_CONNECTION {
            get {
                return ResourceManager.GetString("MANUAL_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as finished.
        /// </summary>
        public static string MARK_AS_FINISHED {
            get {
                return ResourceManager.GetString("MARK_AS_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as new.
        /// </summary>
        public static string MARK_AS_NEW {
            get {
                return ResourceManager.GetString("MARK_AS_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books found in your library.
        /// </summary>
        public static string NO_BOOKS_FOUND {
            get {
                return ResourceManager.GetString("NO_BOOKS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No servers found.
        /// </summary>
        public static string NO_SERVERS_FOUND {
            get {
                return ResourceManager.GetString("NO_SERVERS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show.
        /// </summary>
        public static string NOTHING_TO_SHOW {
            get {
                return ResourceManager.GetString("NOTHING_TO_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page gap.
        /// </summary>
        public static string PAGE_GAP {
            get {
                return ResourceManager.GetString("PAGE_GAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string PAGINATION_INFO {
            get {
                return ResourceManager.GetString("PAGINATION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph Spacing.
        /// </summary>
        public static string PARAGRAPH_SPACING {
            get {
                return ResourceManager.GetString("PARAGRAPH_SPACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string PROGRESS {
            get {
                return ResourceManager.GetString("PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Time.
        /// </summary>
        public static string READ_TIME {
            get {
                return ResourceManager.GetString("READ_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RETRY {
            get {
                return ResourceManager.GetString("RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for servers.
        /// </summary>
        public static string SEARCHING_SERVERS {
            get {
                return ResourceManager.GetString("SEARCHING_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string SERVER {
            get {
                return ResourceManager.GetString("SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        public static string SERVER_URL {
            get {
                return ResourceManager.GetString("SERVER_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s set things up.
        /// </summary>
        public static string SET_UP {
            get {
                return ResourceManager.GetString("SET_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        public static string SHELF {
            get {
                return ResourceManager.GetString("SHELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string START_DATE {
            get {
                return ResourceManager.GetString("START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string STATS {
            get {
                return ResourceManager.GetString("STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync completed.
        /// </summary>
        public static string SYNC_COMPLETED {
            get {
                return ResourceManager.GetString("SYNC_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Progress.
        /// </summary>
        public static string SYNC_PROGRESS {
            get {
                return ResourceManager.GetString("SYNC_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Indent.
        /// </summary>
        public static string TEXT_INDENT {
            get {
                return ResourceManager.GetString("TEXT_INDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string UNINSTALL {
            get {
                return ResourceManager.GetString("UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Margin.
        /// </summary>
        public static string VERTICAL_MARGIN {
            get {
                return ResourceManager.GetString("VERTICAL_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
    }
}
